version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    tty: true
    ports: 
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - ./backend:/usr/src/app

networks:
  my-network:
    driver: bridge