version: "3.7"

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: "suura"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql:/var/lib/mysql
    ports: 
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    tty: true
    ports: 
      - "3000:3000"
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - my-network

volumes:
  mysql:
networks:
  my-network:
    driver: bridge
