version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    tty: true
    ports: 
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - ./backend:/usr/src/app

  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "suura"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - /home/linode-user/data/mysql:/var/lib/mysql
    ports: 
      - "3306:3306"

volumes:
  /home/linode-user/data/mysql
networks:
  my-network:
    driver: bridge